module.exports = {
  TRIAL_DAYS: 7,
  BASE_DAILY_CREDITS: 2,
  BONUS_DAILY_CREDITS: 1,
  WHATSAPP_SHARES_REQUIRED: 3,
  MAX_RESPONSE_WORDS: 1000,
  PRICING_REDIRECT: '/pricing',
  MIN_SHARE_HASH_LENGTH: 16,
  JSON_BODY_LIMIT: '2mb',
  API_VERSION: '2.1.0',
};
