"""AI Universe multi-agent corporate intelligence package."""

from ai_company.agents import (
    AI_CEO,
    AI_CMO,
    AI_CHIEF_DEVELOPER,
    AI_MEDIA_PRODUCER,
    AI_RISK_OFFICER,
    ALL_AGENTS,
    AGENT_REGISTRY,
    SALES_AGENT_A,
    SALES_AGENT_B,
    SALES_AGENT_C,
    WORKFORCE_AGENTS,
    ai_ceo,
    ai_cmo,
    ai_media_engine,
    chief_developer,
    custom_llm,
    internet_scraper_tool,
    risk_officer,
    sales_agent_a,
    sales_agent_b,
    sales_agent_c,
)
from ai_company.tasks import (
    CORE_TASKS,
    TASK_REGISTRY,
    build_default_crew_inputs,
    ceo_orchestration_task,
    cmo_viral_growth_task,
    risk_enforcement_task,
    sales_b_direct_dm_task,
)

__all__ = [
    "AI_CEO",
    "AI_CMO",
    "AI_MEDIA_PRODUCER",
    "SALES_AGENT_A",
    "SALES_AGENT_B",
    "SALES_AGENT_C",
    "AI_CHIEF_DEVELOPER",
    "AI_RISK_OFFICER",
    "ai_ceo",
    "ai_cmo",
    "ai_media_engine",
    "sales_agent_a",
    "sales_agent_b",
    "sales_agent_c",
    "chief_developer",
    "risk_officer",
    "ALL_AGENTS",
    "WORKFORCE_AGENTS",
    "AGENT_REGISTRY",
    "CORE_TASKS",
    "TASK_REGISTRY",
    "ceo_orchestration_task",
    "cmo_viral_growth_task",
    "sales_b_direct_dm_task",
    "risk_enforcement_task",
    "build_default_crew_inputs",
    "custom_llm",
    "internet_scraper_tool",
]
