"""
AI Universe — Multi-Agent Task Execution Blueprint
====================================================
Operational CrewAI Task definitions mapped to the eight master-brain agents.
These tasks enforce Chairman authorization gates, pricing models, screenshot
tracking, and network safety parameters across the autonomous workforce.
"""

from __future__ import annotations

import logging
from typing import Dict, List

from crewai import Task

from ai_company.agents import (
    ai_ceo,
    ai_cmo,
    ai_media_engine,
    chief_developer,
    risk_officer,
    sales_agent_a,
    sales_agent_b,
    sales_agent_c,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Core task definitions (CrewAI allows at most one async task at pipeline tail)
# ---------------------------------------------------------------------------

CEO_ORCHESTRATION_DESCRIPTION = (
    "Receive the Chairman supreme directive from the god-mode UI. Break down the "
    "target (£1M or variable limits) into granular actionable execution chunks. "
    "Draft a dynamic, structured JSON strategy mapping exact quotas for marketing "
    "and sales departments, including pricing model tiers (£1 quiz tickets, "
    "premium AI subscription ladders, and affiliate commission splits). "
    "Stop the pipeline execution and output a professional 'PROPOSAL' or "
    "'STRATEGY' text report to request the Chairman authorization signature "
    "before releasing tasks. Embed strict administrative authorization validation "
    "prompts compatible with god-mode approve/amend hooks."
)

CEO_ORCHESTRATION_EXPECTED_OUTPUT = (
    "A clear, itemized execution strategy layout embedded with strict "
    "administrative authorization validation prompts."
)

ceo_orchestration_task: Task = Task(
    description=CEO_ORCHESTRATION_DESCRIPTION,
    expected_output=CEO_ORCHESTRATION_EXPECTED_OUTPUT,
    agent=ai_ceo,
    async_execution=False,
)

CMO_VIRAL_GROWTH_DESCRIPTION = (
    "Scan global trend metrics across Reddit, Twitter, and TikTok using scraping "
    "pipelines. Invent raw, high-converting content formats specifically pushing "
    "the 'Share-to-Unlock 24h Premium Free Access' hook for our Uncensored AI. "
    "Delegate video parameters to the AI Media Producer to render 10 to 15 "
    "automated clips daily using local open-source TTS voice profiles and FFmpeg "
    "filters. Maintain screenshot tracking ledgers for every viral frame, "
    "watermark placement coordinate, and click-through attribution tag so the "
    "Chairman can audit distribution performance in god-mode."
)

CMO_VIRAL_GROWTH_EXPECTED_OUTPUT = (
    "A detailed visual content log sheet mapping viral screenshot scripts, "
    "watermark layouts, and automated distribution targets."
)

cmo_viral_growth_task: Task = Task(
    description=CMO_VIRAL_GROWTH_DESCRIPTION,
    expected_output=CMO_VIRAL_GROWTH_EXPECTED_OUTPUT,
    agent=ai_cmo,
    async_execution=False,
)

SALES_B_DIRECT_DM_DESCRIPTION = (
    "Infiltrate tech, AI, gaming, and prize subreddits or Discord logs via mobile "
    "residential proxy routers. Detect active users searching for unrestricted LLMs "
    "or cash quiz giveaways. Draft hyper-personalized, psychologist-level custom "
    "messages addressing their explicit problem vectors, and safely secure "
    "immediate £1 ticket conversions or paid AI subscriptions. Log every engagement "
    "with pricing model applied, proxy session tag, and conversion value for "
    "Supabase migration and Chairman revenue dashboards."
)

SALES_B_DIRECT_DM_EXPECTED_OUTPUT = (
    "A secured database migration log tracking direct lead engagements, proxy tags "
    "used, and direct conversation conversion values."
)

sales_b_direct_dm_task: Task = Task(
    description=SALES_B_DIRECT_DM_DESCRIPTION,
    expected_output=SALES_B_DIRECT_DM_EXPECTED_OUTPUT,
    agent=sales_agent_b,
    async_execution=False,
)

RISK_ENFORCEMENT_DESCRIPTION = (
    "Audit every background outbound action generated by marketing and sales. "
    "Inject mandatory random human-like spacing delays (3 to 7 minutes breaks) "
    "between DMs and emails to defeat social media tracking traps. Enforce strict "
    "anti-ban rules, monitor burner accounts health indicators, and protect Stripe "
    "gateways against high-frequency transaction blocks. Publish security parameter "
    "thresholds (max messages per hour, proxy rotation cadence, payment velocity "
    "caps) and halt any thread that violates compliance until Risk clearance is "
    "restored."
)

RISK_ENFORCEMENT_EXPECTED_OUTPUT = (
    "A real-time network safety clearance log certifying 100% compliance across "
    "all autonomous threads."
)

risk_enforcement_task: Task = Task(
    description=RISK_ENFORCEMENT_DESCRIPTION,
    expected_output=RISK_ENFORCEMENT_EXPECTED_OUTPUT,
    agent=risk_officer,
    async_execution=True,
)


# ---------------------------------------------------------------------------
# Task registry for Crew builders, schedulers, and god-mode dispatch
# ---------------------------------------------------------------------------

CORE_TASKS: List[Task] = [
    ceo_orchestration_task,
    cmo_viral_growth_task,
    sales_b_direct_dm_task,
    risk_enforcement_task,
]

TASK_REGISTRY: Dict[str, Task] = {
    "ceo_orchestration": ceo_orchestration_task,
    "cmo_viral_growth": cmo_viral_growth_task,
    "sales_b_direct_dm": sales_b_direct_dm_task,
    "risk_enforcement": risk_enforcement_task,
}

# Named workforce agent bindings for extended crew compositions.
WORKFORCE_AGENT_REGISTRY = {
    "ai_ceo": ai_ceo,
    "ai_cmo": ai_cmo,
    "ai_media_engine": ai_media_engine,
    "sales_agent_a": sales_agent_a,
    "sales_agent_b": sales_agent_b,
    "sales_agent_c": sales_agent_c,
    "chief_developer": chief_developer,
    "risk_officer": risk_officer,
}


def get_task(task_id: str) -> Task:
    """
    Resolve a task identifier to its CrewAI Task instance.

    Args:
        task_id: Registry key (e.g. 'ceo_orchestration', 'risk_enforcement').

    Raises:
        KeyError: If the identifier is unknown.
    """
    key = (task_id or "").strip().lower()
    if key not in TASK_REGISTRY:
        known = ", ".join(sorted(TASK_REGISTRY))
        raise KeyError(f"Unknown task_id '{task_id}'. Known ids: {known}")
    return TASK_REGISTRY[key]


def describe_task_pipeline() -> List[Dict[str, str]]:
    """Return a serializable overview of the four core execution tasks."""
    return [
        {
            "task_id": task_id,
            "agent_role": task.agent.role if task.agent else "unassigned",
            "expected_output": task.expected_output,
            "async_execution": str(getattr(task, "async_execution", False)),
        }
        for task_id, task in TASK_REGISTRY.items()
    ]


def build_default_crew_inputs(chairman_directive: str) -> Dict[str, str]:
    """
    Package Chairman god-mode input for CEO orchestration kickoff.

    Args:
        chairman_directive: Raw directive text from the god-mode UI composer.

    Returns:
        Input dictionary suitable for Crew.kickoff(inputs=...).
    """
    directive = (chairman_directive or "").strip()
    if not directive:
        raise ValueError("chairman_directive must be a non-empty string.")
    return {
        "chairman_directive": directive,
        "authorization_state": "PENDING_CHAIRMAN_SIGNATURE",
        "pricing_models": "quiz_ticket_1gbp,premium_ai_subscription,affiliate_50pct",
        "screenshot_tracking": "enabled",
        "security_parameters": "dm_delay_3_7min,proxy_rotation,residential_mobile,stripe_velocity_cap",
    }


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print(f"Core tasks loaded : {len(CORE_TASKS)}")
    print(f"Workforce agents  : {len(WORKFORCE_AGENT_REGISTRY)}")
    for task_id, task in TASK_REGISTRY.items():
        agent_name = task.agent.role if task.agent else "N/A"
        print(f"  - [{task_id}] -> {agent_name}")
    print("\nPipeline snapshot:")
    for row in describe_task_pipeline():
        print(f"  {row['task_id']}: async={row['async_execution']}, agent={row['agent_role']}")
    sample_inputs = build_default_crew_inputs(
        "Scale Quiz ticket revenue to £1M in 30 days with zero Stripe blocks."
    )
    print("\nSample crew inputs:")
    for key, value in sample_inputs.items():
        print(f"  {key}: {value}")
